steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cohesive-mender-411409/testimage', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/cohesive-mender-411409/testimage']