reproducibility:
  seed: 123

data:
  dir: "data/raw/grapevine-leaves-image-dataset/Grapevine_Leaves_Image_Dataset"
  transform_level: "light"
  batch_size: 32
  val_split: 0.2
  num_workers: 6

model:
  #model_name: "efficientnet_b0" # or resnetv2_50t
  model_name: "CNN"
  num_classes: 5
  drop_rate: 0.3
  pretrained: true


optimization:
  lr_pretrained: 1e-5
  lr_final: 1e-4
  optimizer: "AdamW"
  criterion: "cross_entropy"

training:
  max_epochs: 20

logging:  
  log_every_n_steps: 5
