name: Python application
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        coverage run -m pytest tests/
        coverage html --title="DTU 02476 Group 100 Project Coverage Report"
    - name: Upload pytest test results
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
